version: '3.8'

services:
  app:
    image: laravelphp/php-fpm
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      APP_NAME: Laravel
      APP_ENV: production
      APP_KEY: base64:0+kQNmjEc9HBagVSPoAPLSjyDUbnc+wr/3fqMRXa4Ew=
      APP_DEBUG: 'true'
     
